### ISSUE TITLE
Need velocity and acceleration values from Nolo IMU (SteamVR)

### ISSUE THREAD

**Issue by TheDeveloperGuy** [NOLOVR/NOLO-Windows-SDK#6]
In order for SteamVR to do pose predictions (which it needs to do for warping etc.), it's necessary to supply it with velocity and acceleration values, as well as angular velocity and acceleration values. It's possible to derive these values from the orientation and position values, but doing so introduces a lot of jitter, which is not present when providing just the position and orientation values. I'm guessing that the position/orientation values that Nolo provides are 'noisy' and SteamVR is doing a filter on them to smooth them out, as there is no jitter if not providing the velocity/acceleration values. It appears that SteamVR does not try to interpolate these values if not provided by the driver (probably due to jitter).

If these values aren't provided (for the controllers at least), then it's not possible to do things like throwing (or anything that relies on the acceleration or velocity of the controllers). These values are certainly available on the hardware side of the Nolo sensors, and so it would be a lot better to use these values than try to interpolate them from the position/orientation values. Even it I put an alpha-beta filter onto the interpolated values, there is still some jitter. If the filter smooths out the values too much, then quick movements are not possible.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang  @Hettylool  I see the new USB-HID SDK has potential to provide these values. I haven't looked closely enough to see if it's providing velocity/acceleration values and whether they are actually from the IMU, or are simulated. 

Can you please give me an update on this? I understand that the hardware needs new firmware for this. Is that correct?

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

Sorry, can i answer for you tomorrow? It is a bit urgent and needs to leave the office，sorry

**Comment by TheDeveloperGuy** [comment]
👍

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang  @Hettylool  Ok, so I've tested this and I can see that the velocity/acceleration values are being supplied by the SDK, but they are not coming from the hardware, they are coming from a software emulation. It's not really possible to do it this way, as you can probably see from the controller jumping all over the place when you use these values. We really need to get the values from the hardware. Is that something that you are working towards?

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
hi
Now we provide simulation values, and the real value that provided by the hardware is being tested. I will finish testing as soon as possible, but we need to reserve the interface for it, we will not always provide the simulation value. No worries.

**Comment by TheDeveloperGuy** [comment]
👍

**Comment by nanospork** [comment]
@GXiaoyang 
Hi! Would it be possible to have the firmware send separately the controller orientation generated by the external sensor and the controller orientation generated by the IMU? It would be very helpful for the OSVR driver we are working on if we could access these values separately, in addition to the velocity and acceleration values! :smile:

**Comment by TheDeveloperGuy** [comment]
@nanospork  AFAIK there is no way to measure orientation from a single beacon that is being picked up from a single point, so there is only the IMU orientation.

**Comment by nanospork** [comment]
@TheDeveloperGuy I mean the overall orientation externally tracked, like with the headset marker. We're doing our own sensor fusion and it would be very useful to have.

**Comment by nanospork** [comment]
At least, I'm under the impression that their proprietary tracking is capable of orientation because when we configured our driver to only use data from the Nolo hardware, the headset marker data came in at a pretty low frequency, like 30 Hz, and doesn't really appear to drift in yaw (at least not as much as the controllers.)

**Comment by TheDeveloperGuy** [comment]
@nanospork You may be under the wrong impression, but I'll let one of the developers clarify that. The headset orientation data is not that good or fast, and it does drift, so the recommendation (from LYRobotix) is to use the headset's orientation data with the NoloVR positional data. I do that and find it a lot more reliable/suitable but YMMV (I give the user the option to go for NoloVR orientation data if they want to). My point was that it's not really possible (if you think about it) to get rotational data from a single tracking point and a single beacon. In almost all cases you're going to be able to get better and more frequent orientation tracking from your HMD than you will from NoloVR headset marker.

**Comment by nanospork** [comment]
Yes, the orientation data from a a headset's IMU is reported at a higher-frequency and generally less noisy, but it drifts.  The orientation provided by the NoloVR headset marker is noisy, but more accurate over time. Our fusion algorithm uses a complementary filter to high-pass the headset IMU while low-passing the NoloVR data. The result is fast, responsive tracking that does not drift in yaw. This is a much better approach than simply taking orientation data from one source.

The trouble is that I cannot do this with the controllers, because I can't access the IMU and external orientation separately in order to combine them. It seems that the external orientation, if calculated at all, is discarded in their current setup. 

You're right, it seems odd that they can get orientation from what seems like a single point, but it certainly appears that that's what they're doing. Perhaps the devs can clarify how that works. At the very least, if there is an IMU in the headset marker, it drifts a lot less than that in my HMD.

**Comment by TheDeveloperGuy** [comment]
There is an IMU in the headset marker and there is some rudimentary method to pick up more or less which direction the base station is relative to the headset (and controller for that matter). Who knows what they're actually doing, but it would seem that at the very least you can tell which IR sensor is having the beam hit it (so get rotational accuracy to about 90 degrees (4 sensors for 360). Maybe you can knock that down to 45 degrees if you get partial hits on 2. I'm guessing from hard-coded recenter buttons everywhere that they haven't solved the issue of drift particularly well.

**Comment by LyuzhouZ** [comment]
Fixed.
